with cleaned_and_renamed as(
  select
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  BRAND,
  SELLER,		
  SELLER_CITY,	
  PRICE,
  DISCOUNT_PERCENT,		
 FINAL_PRICE,	
  RATING,
  REVIEW_COUNT,
  STOCK_AVAILABLE,
  UNITS_SOLD,
  LISTING_DATE,	
  DELIVERY_DAYS,
  WEIGHT_G,	
  WARRANTY_MONTHS,
  COLOR,	
  SIZE,
  RETURN_POLICY_DAYS,	
  IS_RETURNABLE,
  PAYMENT_MODES,
  SHIPPING_WEIGHT_G,
  PRODUCT_SCORE,
  SELLER_RATING 

  from {{ source('flipkart_order_details', 'FLIPKARD') }}
  )
  SELECT * FROM cleaned_and_renamed
